### ISSUE TITLE
Vulnerabilities in dependencies

### ISSUE THREAD

**Issue by Gijutsu** [swedenconnect/swedish-eid-idp#9]
Hi!
Multiple vulnerabilities in your dependencies have been detected by Snyk[1]. For example:
* Arbitrary Code Execution:
  * Vulnerable module: ch.qos.logback:logback-core
  * Introduced through: net.shibboleth.idp:idp-authn-api@3.3.2, net.shibboleth.idp:idp-authn-impl@3.3.2 and others

  * Vulnerable module: ch.qos.logback:logback-classic
  * Introduced through: net.shibboleth.idp:idp-authn-api@3.3.2, net.shibboleth.idp:idp-authn-impl@3.3.2 and others

  * Vulnerable module: commons-collections:commons-collections
  * Introduced through: net.shibboleth.idp:idp-authn-api@3.3.2, net.shibboleth.idp:idp-authn-impl@3.3.2 and others

* Deserialization of Untrusted Data
  * Vulnerable module: com.fasterxml.jackson.core:jackson-databind
  * Introduced through: net.shibboleth.idp:idp-authn-api@3.3.2, net.shibboleth.idp:idp-authn-impl@3.3.2 and others

* Directory Traversal
  * Vulnerable module: org.springframework:spring-webmvc
  * Introduced through: org.springframework.mobile:spring-mobile-device@1.1.5.RELEASE

* Elliptic Curve Key Disclosure
  * Vulnerable module: com.nimbusds:nimbus-jose-jwt
  * Introduced through: se.litsec.sweid.idp:shibboleth-authn-support@1.3.1

* Invalid Elliptic Curve Attack
  * Vulnerable module: com.nimbusds:nimbus-jose-jwt
  * Introduced through: se.litsec.sweid.idp:shibboleth-authn-support@1.3.1

* XML External Entity (XXE) Injection
  * Vulnerable module: jstl:jstl
  * Introduced through: jstl:jstl@1.1.2

[1] https://snyk.io/test/github/elegnamnden/swedish-eid-idp/master%2Fidp?tab=issues&severity=high&severity=medium&severity=low

**Comment by martin-lindstrom** [comment]
Thank you!

For the vulnerabilities introduced via Shibboleth jars we should report this to the Shib team I guess.

Some comments about the others:

- We use Nimbus for handling signed Signature Activation Data JWT:s and do not make use of Elliptic curves there.

- About XXE injection via JSTL, we do not use any JSTL functions that parse or otherwise handle XML-data. In fact, we only use c:set, c:foreach and those functions.

Will look into this more in detail after the weekend.

**Comment by martin-lindstrom** [comment]
Fixed in PR #35
